server:
  port: 8081
spring: 
    application:
        name: suspecious-activity-email

    kafka:
        bootstrap-servers: localhost:9092
    mail:
        host: localhost
        port: 1025
        username: ""
        password: ""
        properties:
            mail:
                smtp:
                auth: false
                starttls:
                    enable: false
            protocol: smtp
kafka:
    group-id: suspicious_activity_group